name: dot_puzzle
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  equatable: ^2.0.3
  http: ^0.13.4
  image: ^3.1.1
  debounce_throttle: ^2.0.0
  easy_debounce: ^2.0.2+1
  fast_noise: ^1.0.1
  multi_value_listenable_builder: ^0.0.2
  vibration: 1.7.4-nullsafety.0
  just_audio: ^0.9.20
  google_fonts: ^2.3.1
  confetti: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/audio/
